[2024-09-23T00:44:14.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T00:44:14.122+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:44:04.292600+00:00 [queued]>
[2024-09-23T00:44:14.135+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:44:04.292600+00:00 [queued]>
[2024-09-23T00:44:14.136+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-23T00:44:14.159+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_into_snowflake> on 2024-09-23 00:44:04.292600+00:00
[2024-09-23T00:44:14.176+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=287) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-23T00:44:14.179+0000] {standard_task_runner.py:72} INFO - Started process 290 to run task
[2024-09-23T00:44:14.180+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mercadolivre_scraper_to_snowflake_dag', 'insert_into_snowflake', 'manual__2024-09-23T00:44:04.292600+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/mercado_livre.py', '--cfg-path', '/tmp/tmpo377ajwc']
[2024-09-23T00:44:14.182+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask insert_into_snowflake
[2024-09-23T00:44:14.256+0000] {task_command.py:467} INFO - Running <TaskInstance: mercadolivre_scraper_to_snowflake_dag.insert_into_snowflake manual__2024-09-23T00:44:04.292600+00:00 [running]> on host 6a22fc4abd55
[2024-09-23T00:44:14.369+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mercadolivre_scraper_to_snowflake_dag' AIRFLOW_CTX_TASK_ID='insert_into_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:44:04.292600+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-23T00:44:04.292600+00:00'
[2024-09-23T00:44:14.372+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-23T00:44:14.372+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-23T00:44:14.373+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_snowflake state:running start_date:2024-09-23 00:44:14.123111+00:00
[2024-09-23T00:44:14.373+0000] {logging_mixin.py:190} INFO - Dag name:mercadolivre_scraper_to_snowflake_dag and current dag run status:running
[2024-09-23T00:44:14.373+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T00:44:14.394+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mercado_livre.py", line 33, in insert_into_snowflake
    products = context['ti'].xcom_pull(key='products', task_ids='scrape_products')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3691, in xcom_pull
    return _xcom_pull(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 632, in _xcom_pull
    return XCom.deserialize_value(first)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 720, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 715, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 118, in object_hook
    return deserialize(dct)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 255, in deserialize
    raise ImportError(
ImportError: schema.ProductData was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-09-23T00:44:14.422+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-23T00:44:14.423+0000] {logging_mixin.py:190} INFO - Task start:2024-09-23 00:44:14.123111+00:00 end:2024-09-23 00:44:14.421624+00:00 duration:0.298513
[2024-09-23T00:44:14.424+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_into_snowflake> dag:<DAG: mercadolivre_scraper_to_snowflake_dag> dagrun:<DagRun mercadolivre_scraper_to_snowflake_dag @ 2024-09-23 00:44:04.292600+00:00: manual__2024-09-23T00:44:04.292600+00:00, state:running, queued_at: 2024-09-23 00:44:04.302473+00:00. externally triggered: True>
[2024-09-23T00:44:14.424+0000] {logging_mixin.py:190} INFO - Failure caused by schema.ProductData was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-09-23T00:44:14.425+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=mercadolivre_scraper_to_snowflake_dag, task_id=insert_into_snowflake, run_id=manual__2024-09-23T00:44:04.292600+00:00, execution_date=20240923T004404, start_date=20240923T004414, end_date=20240923T004414
[2024-09-23T00:44:14.448+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T00:44:14.449+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task insert_into_snowflake (schema.ProductData was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration; 290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mercado_livre.py", line 33, in insert_into_snowflake
    products = context['ti'].xcom_pull(key='products', task_ids='scrape_products')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3691, in xcom_pull
    return _xcom_pull(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 632, in _xcom_pull
    return XCom.deserialize_value(first)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 720, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 715, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 118, in object_hook
    return deserialize(dct)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 255, in deserialize
    raise ImportError(
ImportError: schema.ProductData was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-09-23T00:44:14.477+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-23T00:44:14.501+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T00:44:14.503+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
